### ISSUE TITLE
cant build LoginKit_Example

### ISSUE THREAD

**Issue by RGreinacher** [TigerWolf/LoginKit#1]
- [x] outdated `NimbleXCTestHandler`, copying the [newest file](https://github.com/Quick/Nimble/blob/758cc9b80e0978d7b86b7729f90cd52ee270cb02/Sources/Nimble/Adapters/NimbleXCTestHandler.swift) will solve this
- [x] compile error; <unknown>:0: error: no such file or directory: '~/LoginKit/Example/LoginKit_ExampleTests/Test2.swift'

**Comment by TigerWolf** [comment]
Thanks for the report. Will update the example when I get a chance.

**Comment by TigerWolf** [comment]
I have updated the project. Can you try it out again?

**Comment by RGreinacher** [comment]
Thank you very much for the quick reply! It works like a charm! : )

**Comment by TigerWolf** [comment]
Any features you are interested in and would like? This is my first swift library so feedback would be welcome.

For example a German translation?
